import turtle
tao = turtle.Pen()
tao.shape('turtle')
tao.circle(120)
tao.penup()
tao.goto(0,-20)
tao.pendown()
tao.circle(140)
tao.penup()
tao.goto(0,60)
tao.pendown()
tao.circle(60)
tao.left(90)
tao.forward(120)
tao.penup()
tao.goto(0,120)
tao.pendown()
tao.left(90)
tao.penup()
tao.goto(60,120)
tao.pendown()
tao.forward(120)
tao.done()

